### PR TITLE
Functionalization

### PR DESCRIPTION
**Pull request by rag4214**
Made all of the switch commands functions, throwing errors if something cannot be done, returning a string if it does complete.

### CODE REVIEW

**Comment by evanextreme** [comment]
This is tested working?

**Comment by rag4214** [comment]
I'm not exactly sure what you mean

**Comment by evanextreme** [comment]
sorry, super dead today
has this been tested on mac/linux to ensure compatibility?

**Comment by rag4214** [comment]
Just ran into a very niche bug, trying to fix now and I'll push when it is

**Comment by rag4214** [comment]
There we go, everything is fixed and has been tested on both of my machines

**Pull request merged**
